<a href="https://colab.research.google.com/github/76027/prir/blob/main/Lab10/Zadanie1_lab10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import tensorflow as tf
from math import *
import numpy as np


class M_prostokatow:
    def __init__(self,a,b,n):
        self.a = a
        self.b = b
        self.n = n

    def f(self,x):
        return 2*x



    def oblicz(self):

        s = 0
        h = (self.b - self.a) / self.n
        for i in range(1,self.n):
            s += self.f(self.a) * h
            self.a += h
        return s



class M_trapezow:
    def __init__(self, a, b, n):
        self.a = a
        self.b = b
        self.n = n





    def f(self,x):
        return 2*x


    def oblicz(self):
        s = 0
        h = (self.b - self.a) / self.n
        for i in range(1,self.n+1):
            s += ((self.f(self.a) + self.f(self.a+h)) * h) / 2
            self.a += h
        return s

class M_Simpsona():
    def __init__(self, a, b, n):
        self.n = n
        self.a = a
        self.b = b



    def f(self, x):
        return 2*x

    def oblicz(self):
        s = 0
        st = 0
        h = (self.b - self.a) / self.n
        for i in range(1,self.n+1):
            x = self.a + i * h
            st += self.f(x - h / 2)
            if (i < self.n):
                s += self.f(x)

        s = h / 6 * (self.f(self.a) + self.f(self.b) + 2 * s + 4 * st)
        return s

Tworzę klasy z z zaimplemontowanymi metodami trapezów, prostokątów i Simpsona,obliczające pole pod całką 2*x

In [39]:
x = np.arange(1,10,1)
x = np.asarray(x)
print(x)

[1 2 3 4 5 6 7 8 9]


Tworzę macierz elementów z przedziału od 1 do 10 z krokiem 1

In [40]:
print("Metoda prostokatow")
met_pro = [M_prostokatow(i,i+1,3000).oblicz() for i in x]
met_pro = np.asarray(met_pro)
print(met_pro)

print("Metoda trapezow")
met_tra = [M_trapezow(i,i+1,3000).oblicz() for i in x]
met_tra = np.asarray(met_tra)
print(met_tra)

print("Metoda Simpsona")
met_sim = [M_Simpsona(i,i+1,3000).oblicz() for i in x]
met_sim = np.asarray(met_sim)
print(met_sim)


Metoda prostokatow
[ 2.99833356  4.99766689  6.99700022  8.99633356 10.99566689 12.99500022
 14.99433356 16.99366689 18.99300022]
Metoda trapezow
[ 3.  5.  7.  9. 11. 13. 15. 17. 19.]
Metoda Simpsona
[ 3.  5.  7.  9. 11. 13. 15. 17. 19.]


Wypisuje wyniki z działania funkcji w przedziałach [1:2] .... [9:10] przy 3000 iteracji


In [41]:
model_p = tf.keras.models.Sequential([
  tf.keras.layers.Dense(1, input_shape=(1, )),
  # tf.keras.layers.Dense(3,activation='relu'),
  # tf.keras.layers.Dense(4,activation='sigmoid'),
  # tf.keras.layers.Dense(3,activation='relu'),
  tf.keras.layers.Dense(1)
])

model_t = tf.keras.models.Sequential([
  tf.keras.layers.Dense(1, input_shape=(1, )),
  # tf.keras.layers.Dense(3,activation='relu'),
  # tf.keras.layers.Dense(4,activation='sigmoid'),
  # tf.keras.layers.Dense(3,activation='relu'),
  tf.keras.layers.Dense(1)
])

model_S = tf.keras.models.Sequential([
  tf.keras.layers.Dense(1, input_shape=(1, )),
  # tf.keras.layers.Dense(3,activation='relu'),
  # tf.keras.layers.Dense(4,activation='sigmoid'),
  # tf.keras.layers.Dense(3,activation='relu'),
  tf.keras.layers.Dense(1)
])



Tworzę modele dla każdej metody

In [61]:

model_p.compile(optimizer=tf.optimizers.Adam(learning_rate=0.1), loss='mean_squared_error')


model_t.compile(optimizer=tf.optimizers.Adam(learning_rate=0.1), loss='mean_squared_error')

model_S.compile(optimizer=tf.optimizers.Adam(learning_rate=0.1), loss='mean_squared_error')

Porównuję działanie dwóch optymizatorów, optymizator adam z rating rate =0.1, optymizator mean_squared_error wydaje się dokładniejszy w tym przykładzie.


In [62]:
model_p.fit(x,met_pro,epochs = 50)

model_t.fit(x,met_tra,epochs = 50)

model_S.fit(x,met_sim,epochs = 50)

Epoch 1/50
1/1 [==============================] - 0s 234ms/step - loss: 9.3353
Epoch 2/50
1/1 [==============================] - 0s 4ms/step - loss: 2.7020
Epoch 3/50
1/1 [==============================] - 0s 2ms/step - loss: 0.3089
Epoch 4/50
1/1 [==============================] - 0s 4ms/step - loss: 1.7740
Epoch 5/50
1/1 [==============================] - 0s 5ms/step - loss: 3.4607
Epoch 6/50
1/1 [==============================] - 0s 4ms/step - loss: 3.1350
Epoch 7/50
1/1 [==============================] - 0s 6ms/step - loss: 1.7434
Epoch 8/50
1/1 [==============================] - 0s 3ms/step - loss: 0.5775
Epoch 9/50
1/1 [==============================] - 0s 3ms/step - loss: 0.2454
Epoch 10/50
1/1 [==============================] - 0s 4ms/step - loss: 0.6327
Epoch 11/50
1/1 [==============================] - 0s 3ms/step - loss: 1.2265
Epoch 12/50
1/1 [==============================] - 0s 4ms/step - loss: 1.5571
Epoch 13/50
1/1 [==============================] - 0s 3ms/step - loss: 

Trenuję modele,po 50 epok

In [63]:
print("Przewidywania metody prostokatow")
p = model_p.predict(x)
print(p.flatten())
print("######Wynik z metody prostokatow#######")
print(met_pro)
print("###################")
srednia = 0
for i in range(len(x)):
  
  srednia += abs(p[i]-met_pro[i])
  print("Roznica miedzy wynikami: ",abs(p[i]-met_pro[i]))

srednia = srednia/len(x)
print("Srednia arytmetyczna bledow: ",srednia)


Przewidywania metody prostokatow
[ 2.9342332  4.944697   6.955161   8.965625  10.976088  12.986552
 14.997015  17.00748   19.017944 ]
######Wynik z metody prostokatow#######
[ 2.99833356  4.99766689  6.99700022  8.99633356 10.99566689 12.99500022
 14.99433356 16.99366689 18.99300022]
###################
Roznica miedzy wynikami:  [0.06410027]
Roznica miedzy wynikami:  [0.05296993]
Roznica miedzy wynikami:  [0.04183912]
Roznica miedzy wynikami:  [0.03070831]
Roznica miedzy wynikami:  [0.01957893]
Roznica miedzy wynikami:  [0.00844765]
Roznica miedzy wynikami:  [0.00268173]
Roznica miedzy wynikami:  [0.01381302]
Roznica miedzy wynikami:  [0.02494431]
Srednia arytmetyczna bledow:  [0.02878703]


In [64]:
print("Przewidywania metody trapezow")
t = model_t.predict(x)
print(t.flatten())
print("######Wynik z metody trapezow#######")
print(met_tra)
print("###################")
srednia = 0
for i in range(len(x)):
  
  srednia += abs(t[i]-met_tra[i])
  print("Roznica miedzy wynikami: ",abs(p[i]-met_tra[i]))

srednia = srednia/len(x)
print("Srednia arytmetyczna bledow: ",srednia)


Przewidywania metody trapezow
[ 2.9916205  5.0219812  7.0523424  9.082703  11.113063  13.143424
 15.173783  17.204145  19.234507 ]
######Wynik z metody trapezow#######
[ 3.  5.  7.  9. 11. 13. 15. 17. 19.]
###################
Roznica miedzy wynikami:  [0.06576681]
Roznica miedzy wynikami:  [0.0553031]
Roznica miedzy wynikami:  [0.04483891]
Roznica miedzy wynikami:  [0.03437519]
Roznica miedzy wynikami:  [0.02391243]
Roznica miedzy wynikami:  [0.01344776]
Roznica miedzy wynikami:  [0.002985]
Roznica miedzy wynikami:  [0.00748062]
Roznica miedzy wynikami:  [0.01794434]
Srednia arytmetyczna bledow:  [0.11492533]


In [66]:
print("Przewidywania metody Simpsona")
s = model_S.predict(x)
print(s.flatten())
print("######Wynik z metody Simpsona#######")
print(met_sim)
print("###################")
srednia = 0
for i in range(len(x)):
  
  srednia += abs(t[i]-met_sim[i])
  print("Roznica miedzy wynikami: ",abs(p[i]-met_sim[i]))

srednia = srednia/len(x)
print("Srednia arytmetyczna bledow: ",srednia)


Przewidywania metody Simpsona
[nan nan nan nan nan nan nan nan nan]
######Wynik z metody Simpsona#######
[ 3.  5.  7.  9. 11. 13. 15. 17. 19.]
###################
Roznica miedzy wynikami:  [0.06576681]
Roznica miedzy wynikami:  [0.0553031]
Roznica miedzy wynikami:  [0.04483891]
Roznica miedzy wynikami:  [0.03437519]
Roznica miedzy wynikami:  [0.02391243]
Roznica miedzy wynikami:  [0.01344776]
Roznica miedzy wynikami:  [0.002985]
Roznica miedzy wynikami:  [0.00748062]
Roznica miedzy wynikami:  [0.01794434]
Srednia arytmetyczna bledow:  [0.11492533]


Wypisuje wyniki i roznice miedzy przywidywanymi wynikami a wynikami funkcji
Poniżej dla porówaniania trenuję ponownie model dla metody prostokatokatow,w zależności od tego jaki learning rate wybiore wyniki mogą być dokładniejsze albo występuje przetrenowanie modelu

In [67]:
model_p.fit(x,met_pro,epochs = 100)

model_t.fit(x,met_tra,epochs = 100)

model_S.fit(x,met_sim,epochs = 100)

Epoch 1/100
1/1 [==============================] - 0s 5ms/step - loss: 0.0012
Epoch 2/100
1/1 [==============================] - 0s 6ms/step - loss: 0.0080
Epoch 3/100
1/1 [==============================] - 0s 5ms/step - loss: 0.0187
Epoch 4/100
1/1 [==============================] - 0s 4ms/step - loss: 0.0228
Epoch 5/100
1/1 [==============================] - 0s 4ms/step - loss: 0.0169
Epoch 6/100
1/1 [==============================] - 0s 4ms/step - loss: 0.0071
Epoch 7/100
1/1 [==============================] - 0s 3ms/step - loss: 0.0017
Epoch 8/100
1/1 [==============================] - 0s 3ms/step - loss: 0.0039
Epoch 9/100
1/1 [==============================] - 0s 4ms/step - loss: 0.0099
Epoch 10/100
1/1 [==============================] - 0s 4ms/step - loss: 0.0129
Epoch 11/100
1/1 [==============================] - 0s 5ms/step - loss: 0.0101
Epoch 12/100
1/1 [==============================] - 0s 3ms/step - loss: 0.0044
Epoch 13/100
1/1 [==============================] - 0s 4ms/st

In [68]:
print("Przewidywania metody prostokatow")
p = model_p.predict(x)
print(p.flatten())
print("######Wynik z metody prostokatow#######")
print(met_pro)
print("###################")
srednia = 0
for i in range(len(x)):
  
  srednia += abs(p[i]-met_pro[i])
  print("Roznica miedzy wynikami: ",abs(p[i]-met_pro[i]))

srednia = srednia/len(x)
print("Srednia arytmetyczna bledow: ",srednia)


Przewidywania metody prostokatow
[ 2.998693   4.9978576  6.9970217  8.996187  10.995352  12.994515
 14.99368   16.992846  18.99201  ]
######Wynik z metody prostokatow#######
[ 2.99833356  4.99766689  6.99700022  8.99633356 10.99566689 12.99500022
 14.99433356 16.99366689 18.99300022]
###################
Roznica miedzy wynikami:  [0.00035954]
Roznica miedzy wynikami:  [0.00019073]
Roznica miedzy wynikami:  [2.1457672e-05]
Roznica miedzy wynikami:  [0.00014591]
Roznica miedzy wynikami:  [0.00031471]
Roznica miedzy wynikami:  [0.00048447]
Roznica miedzy wynikami:  [0.00065327]
Roznica miedzy wynikami:  [0.00082207]
Roznica miedzy wynikami:  [0.00098991]
Srednia arytmetyczna bledow:  [0.00044245]


Model jest dokładny w zbiorze treningowym,poniżej sprawdzę go poza zbiorem

In [78]:
print("Wynik metody w przedziale (11;12): ",M_prostokatow(11,12,3000).oblicz())
print("Wynik działania modelu: ",float(model_p.predict((11,))))

Wynik metody w przedziale (11;12):  22.99166688889011
Wynik działania modelu:  22.990341186523438
